server:
  # 运行端口号
  port: 8011

mq:
  # 生产者、控制台访问密钥（放在请求头部）
  secretKey: test_secret_key
  # 消息通道的缓冲空间大小（消息队列的容量）
  messageChanBuffer: 10000
  # 推送消息的速度（{pushMessagesSpeed}秒/一批消息）
  pushMessagesSpeed: 1
  # 单批次推送的消息数量
  sendCount: 5
  # 消息推送失败后的重试次数
  sendRetryCount: 3
