server:
  # 运行端口号
  port: 8011

mq:
  # 生产者、控制台访问密钥（放在请求头部）
  secretKey: test_secret_key
  # 消息通道的缓冲空间大小（消息队列的容量）
  messageChanBuffer: 10000
  # 推送消息的速度（{pushMessagesSpeed}秒/一批消息）
  pushMessagesSpeed: 1
  # 单批次推送的消息数量
  sendCount: 5
  # 消息推送失败后的重试次数
  sendRetryCount: 3
  # 持久化文件存储路径
  persistentPath: ./data.csv
  # 是否进行持久化（1：是。0：否）
  isPersistent: 1
  # 数据恢复策略（0：清空本地数据，不进行数据恢复。1：将本地数据恢复到内存）
  recoveryStrategy: 1
  # 两次持久化的间隔时间（单位：秒）
  persistentTime: 2
  # 重新推送消息的速度（{rePushSpeed}秒/一批消息）
  rePushSpeed: 5
  # 消息清理时间阈值（当消息存在{clearTime}秒后，删除该消息）
  clearTime: 2592000