server:
  # 运行端口号
  port: 8011

mq:
  # 消息通道的缓冲空间大小（消息队列的容量）
  messageChanBuffer: 100
  # 推送消息的速度（{pushMessagesSpeed}秒/一批消息）
  pushMessagesSpeed: 1
  # 单批次推送的消息数量
  sendCount: 5
  # 消息推送失败后的重试次数
  sendRetryCount: 3

  # 未消费消息记录通道的缓冲空间大小
  unconsumeLogChanBuffer: 100
  # 已经消费消息记录通道的缓冲空间大小
  consumeLogChanBuffer: 100
