server:
  # 运行端口号
  port: 8011

mq:
  # 生产者、控制台访问密钥（放在请求头部）
  secretKey: dpmq

  # 消息通道的缓冲空间大小（消息队列的容量）
  messageChanBuffer: 1000000

  # 推送消息的速度（{pushMessagesSpeed}秒/一批消息）
  pushMessagesSpeed: 1
  # 单批次推送的消息数量
  sendCount: 100
  # 消息推送失败后的立即重试的次数
  sendRetryCount: 1

  # 持久化文件
  persistentFile: data
  # 是否进行持久化（1：是。0：否）
  isPersistent: 1
  # 数据恢复策略（0：清空本地数据，不进行数据恢复。1：将本地数据恢复到内存）
  recoveryStrategy: 0
  # 两次持久化的间隔时间（单位：秒）
  persistentTime: 5

  # 是否开启自动重推未确认消费消息功能（1：是。0：否）
  isRePush: 1
  # 是否开启自动清理过期消息功能（1：是。0：否）
  isClean: 1

  # 检查消息的速度（{rePushSpeed}秒/一批消息）
  checkSpeed: 5

  # 消息清理时间阈值（当消息存在{clearTime}秒后，删除该消息）
  cleanTime: 259200